version: '2'

services:
   db:
     image: mysql:5.7
     container_name: mysql_db
     volumes:
       - ./.db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: mysqlpassword1
       MYSQL_DATABASE: default

   web:
     image: mchauvel/php-pdo-mysql
     container_name: apache-php
     ports:
       - '8080:80'
     restart: always
     volumes:
       - .:/var/www/html  
       - ./php.ini:/usr/local/etc/php/conf.d/docker-php-ext-pdo_mysql.ini

       
   phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '8082:80'
    environment:
      PMA_USER: root
      PMA_PASSWORD: mysqlpassword1
      PMA_HOST: db

